left_root: "C:/pdrive_local/"
right_root: "p:/"

soft_delete:
    enabled: true
    max_size_mb: 20

conflict_policy:
    modify_modify: clash
    new_new: clash
    metadata_conflict: clash

ignore:
    extensions:
      - .tmp
      - .bak
    filenames_prefix:
      - .
    filenames_exact:
      - thumbs.db

email:
    enabled: false

logging:
    level: INFO
    file_path: sync.log